version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=3 #optional you can specify the name PEERS=pper1,peer2,peer3
      - PEERDNS=auto #optional point at dns server running on your wireguard server
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /opt/wireguard-server/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp #exposing the port
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
